---
title: "Untitled"
output: html_document
date: "2026-01-21"
---


```{r}

library(tidyverse)
library(cowplot)
theme_set(theme_cowplot(font_size = 15, rel_small = 1, rel_tiny = 1, rel_large = 1))

```

# Load
```{r}

combined_protein <- read_tsv("21-08-25_C18L_replicates_MaxLFQ_TopAll_area_MBR_normalize/combined_protein.tsv")

```

# Filter MaxLFQ intensities
```{r}

# Remove decoys and contaminants
Protein_ID <- combined_protein$`Protein ID`
combined_protein <- combined_protein %>% filter(str_detect(Protein_ID, "Vfaba"))
rm(Protein_ID)
  
# Remove rows with zeroes only
combined_protein <- combined_protein[rowSums(combined_protein[, 75:89])!=0, ] # 883.
df <- combined_protein[rowSums(combined_protein[, 75:89])==0, ]

# Frequency distributions for Combined Total Peptides and Combined Spectral Counts
ggplot(combined_protein) +
  geom_histogram(aes(x = `Combined Total Peptides`), color = 'black', fill = 'red', bins = 91) + 
  xlab('Combined Total Peptides') +
  ylab('Frequency') +
  geom_vline(xintercept=2, color = "grey50", linewidth = 0.75) +
  NULL
summary(combined_protein$`Combined Total Peptides`)

ggplot(combined_protein) +
  geom_histogram(aes(x = `Combined Spectral Count`), color = 'black', fill = 'red', bins = 91) + 
  xlab('Combined Spectral Count') +
  ylab('Frequency') +
  geom_vline(xintercept=3, color = "grey50", linewidth = 0.75) + 
  NULL
summary(combined_protein$`Combined Spectral Count`)

protein_count <- tibble(`Before filtering` = nrow(combined_protein), 
                        `After Combined Total Peptides >= 2` = filter(combined_protein, 
                                                                      `Combined Total Peptides` >= 2) %>% nrow(),
                        `After Combined Spectral Count >= 3` = filter(combined_protein, 
                                                                      `Combined Spectral Count` >= 3) %>% nrow(),
                        `After both criteria applied` = filter(combined_protein, `Combined Total Peptides` >= 2 | `Combined Spectral Count` >= 3) %>% nrow()) 

# Frequency distribution for number of proteins vs number of replicates
ggplot(combined_protein) +
  geom_histogram(aes(x = `N_replicates`), color = 'black', fill = 'red', bins = 91) + 
  xlab('Number of replicates') +
  ylab('Frequency') +
  xlim(0,16) + 
  NULL

# Combined Total Peptides >= 2 or Combined Spectral Counts >= 2.
combined_protein <- combined_protein %>% 
  filter(`Combined Total Peptides` >= 2 | `Combined Spectral Count` >= 3) 

# Select columns.
protein_data <- combined_protein %>% dplyr::select(1, 75:89)
colnames(protein_data)[2:16] <- gsub (" MaxLFQ Intensity", "", colnames(protein_data)[2:16])

# Change order of replicates
protein_data <- cbind(protein_data[,1], protein_data[,11:16], protein_data[,2:10])

```

# Add functional annotations and save
```{r}

FabaHomologues <- read_delim("data/FabaHomologues(FabaHomologues).csv", delim = ";") # Ignore warning. 32322 annotations.

FabaHomologues <- FabaHomologues %>% 
  dplyr::select(`Protein ID TJ`= geneID_HedinV2, 
         `GeneralAnnotation TJ` = GeneralAnnotation,
         `mercator4v6.0` = mercator4v6.0, 
         `prot-scriber` = `prot-scriber`,
         `swissprot` = swissprot) %>% 
  distinct() # 30855 annotations.

protein_data <- protein_data %>% left_join(FabaHomologues, by = c("Protein" = "Protein ID TJ"))

# Convert "no annotation" in swissprot column to NA
protein_data$swissprot <- ifelse(protein_data$swissprot=="no annotation", NA, protein_data$swissprot)
protein_data$`prot-scriber` <- ifelse(protein_data$`prot-scriber`=="no annotation", NA, protein_data$`prot-scriber`)
protein_data$mercator4v6.0 <- ifelse(protein_data$mercator4v6.0=="not classified", NA, protein_data$mercator4v6.0)
protein_data$swissprot <- ifelse(protein_data$swissprot==" no annotation", NA, protein_data$swissprot)
protein_data$`prot-scriber` <- ifelse(protein_data$`prot-scriber`==" no annotation", NA, protein_data$`prot-scriber`)
protein_data$mercator4v6.0 <- ifelse(protein_data$mercator4v6.0==" not classified", NA, protein_data$mercator4v6.0)

# Save
write_tsv(protein_data, "21-08-25_C18L_replicates_MaxLFQ_TopAll_area_MBR_normalize/combined_protein_preprocessed.tsv")

```
